services:
  backend:
    build:
      context: ./packages/api
    ports:
      - "4000:4000"
    volumes:
      - ./packages/api:/usr/src/app
    env_file:
      - ./packages/api/.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./packages/api/.env

volumes:
  postgres_data:
