server {
    listen 80;
    server_name blackbox-training.giize.com;

    # HTTPアクセスはHTTPSにリダイレクト
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name blackbox-training.giize.com;

    # SSL 証明書パス
    ssl_certificate /etc/letsencrypt/live/blackbox-training.giize.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/blackbox-training.giize.com/privkey.pem;

    # SSL セキュリティ設定
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root /usr/share/nginx/html;
    index index.html;

    location /.well-known/acme-challenge/ {
    root /var/www/html;
    }

    # API を backend に転送
    location /api/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 画像パス（/images と /postImage）を backend に転送
    location ^~ /images/ {
        proxy_pass http://backend:3000/images/;
    }
    location ^~ /postImage/ {
        proxy_pass http://backend:3000/postImage/;
    }

    # SPA用フォールバック
    location / {
        try_files $uri /index.html;
    }
}
