import type { Metadata } from "next";
import { notoSansJp } from "@/lib/fonts";
import "./globals.css";
import { Footer } from "@/components/Footer";


export const metadata: Metadata = {
  title: "Livelog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSansJp.variable}>
      <body className="antialiased flex flex-col min-h-screen">
        {children}
        <Footer />
      </body>
    </html>
  );
}
