import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { notoSansJp } from "@/lib/fonts";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSansJp.variable}>
      <body className="antialiased flex flex-col min-h-screen">
        <header className="p-4"><p className="text-4xl">header</p></header>
        <main className="p-4 md:p-8 flex-1 max-w-7xl mx-auto w-full">
        {children}
        </main>
        <footer><p>footer</p></footer>
      </body>
    </html>
  );
}
