import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/auth";
import { axiosServerClient } from "@/lib/api/api-client";
import { Toaster } from "@/components/ui/sonner";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface ApiError {
  code?: string;
  msg: string;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let initialUser = null;
  const cookieStore = await cookies();
  const session = cookieStore.get("session");

  if (!!session) {
    try {
      const response = await axiosServerClient.post("/user", {
        sessionId: session.value,
      });
      initialUser = {
        userId: response.data.loginUser.userId,
        userName: response.data.loginUser.userName,
        userIcon: "/img/userIcon.png",
      };
    } catch (err) {
      const apiError = err as ApiError;
      console.log(
        `ログインユーザー情報の取得に失敗しました。：${apiError.msg}`
      );
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialUser={initialUser}>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
