services:
  next-app:
    platform: linux/arm64
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
