import type { Metadata } from "next";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// 作成したコンポーネントをインポート
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { AuthProvider } from "@/context/AuthContext";
import { LoadingProvider } from "@/context/LoadingContext";
import { Loading } from "@/components/layout/Loading";
import ThemeProvider from "@/theme/theme-provider";

export const metadata: Metadata = {
  // titleをオブジェクト形式で設定
  title: {
    default: "レバ", // デフォルトのタイトル（ホームページ用）
    template: "%s | レバ", // 各ページのタイトルのひな形
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="font-sans bg-background text-foreground">
        <ToastContainer />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LoadingProvider>
            <AuthProvider>
              <Header />
              <Loading />
              <main className="mx-auto max-w-screen-xl py-4 px-8 bg-gray-50 dark:bg-gray-800">
                {/* <div className="px-4 py-4 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-4"> */}
                {children}
                {/* </div> */}
              </main>
              <Footer />
            </AuthProvider>
          </LoadingProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
