import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// 作成したコンポーネントをインポート
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { AuthProvider } from "@/context/AuthContext";
import { LoadingProvider } from "@/context/LoadingContext";
import { Loading } from "@/components/layout/Loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // titleをオブジェクト形式で設定
  title: {
    default: "My Awesome App", // デフォルトのタイトル（ホームページ用）
    template: "%s | My Awesome App", // 各ページのタイトルのひな形
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <LoadingProvider>
          <AuthProvider>
            <Header />
            <Loading />
            <main className="mx-auto max-w-screen-xl  bg-gray-50">
              <div className="px-4 py-4 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
                {children}
              </div>
            </main>
            <Footer />
          </AuthProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
